- name: Gather facts lession
  hosts: all
  vars:
    name: "Om Yadav"
  tasks:
    - name: Debug welcome
      debug: 
        msg: "Welcome {{name}}, you are running code on {{ansible_distribution}} on version {{ansible_distribution_version}}"
