---
- name: Install the apache and start the service 
  hosts: localhost
  tasks:
   - name: install nginx
     yum:
       name: apache
       state: present
   - name: start the Service
     service:
       name: apache
       state: restarted
       enabled: yes

  
 
  
    
