--- 
- name: installed a package and prints the results
  hosts: all
  become: yes

  tasks:
  - name: install the package
    yum:
      name: httpd
      state: present
  - name: start the service
    service:
      name: httpd
      state: started
      enabled: yes
    register: result

  - debug: var=result  