---
- name: Fetch resolv.conf from managed hosts
  hosts: all
  become: yes

  tasks:
    - name: create folder /tmp/resolve-file
      file:
        path: /tmp/resolve-file
        state: directory
      delegate_to: localhost
      
    - name: Fetch resolv.conf
      fetch:
        src: /etc/resolv.conf
        dest: "/tmp/resolve-file/{{ ansible_hostname }}-resolv.conf"
        flat: yes