---
- name: create a file and change the file permission and group
  hosts: all
  become: true
  tasks:
  - name: Create a file
    file:
      path: /tmp/test.file
      state: touch
  - name: change file permission ,owner and group
    file:
      path: /tmp/test.file
      owner: Om
      group: Om
      mode: '0777'