---
- name: installed nginx and start the Service
  hosts: lab
  become: true
  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: present
  - name: start the Service
    service:
      name: nginx
      state: start
      enabled: yes
